version: "3.9"
services:
app:
    depends_on:
        -mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
        -3005:3005
mongo-express:
    image: mongo-express:0.54.0
    depends_on:
        -mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_ADMIN_USERNAME
        ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_ADMIN_PASSWORD
        ME_CONFIG_MONGODB_URL: $DB_URL
mongodb:
    image: mongo:5.0.14
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$DB_PORT
    volumes:
      - db:/data/db
